### ISSUE TITLE
Demo app not available in Belgium.

### ISSUE THREAD

**Issue by ChristopheVersieux** [chRyNaN/Android-Guitar-Tuner#1]
Could you please remove the geographic restriction in the Play Store application?

**Comment by doronbehar** [comment]
Or perhaps upload the app to F-Droid..

**Comment by chRyNaN** [comment]
@ChristopheVersieux I'm in the process of completely refactoring the app (develop branch) to make it more efficient and less error prone. I won't be altering the demo app in the Play Store until the refactor is complete. You can test the application by cloning the project, opening it in Android Studio, and then debugging it. I will add these instructions in more detail to fix another open issue #4 .
