### ISSUE TITLE
Notes are only recognized for a split second and then go back to the note G

### ISSUE THREAD

**Issue by ffpetrovic** [chRyNaN/Android-Guitar-Tuner#54]
Notes are only recognized for a split second and then go back to the note G. Sometimes the note is not even being recognized or even being incorrectly recognized

How do you make this app work?

**Comment by mahdi-malv** [comment]
@chRyNaN Have you checked out this issue?

**Comment by ffpetrovic** [comment]
@mahdi-malv 
I actually made my own tuner application at [https://github.com/ffpetrovic/auxilium](https://github.com/ffpetrovic/auxilium) using the best known audio processing C library called **aubio**, and I still have mediocre accuracy. So it looks like that in order to get very good accuracy, like GuitarTuna ( actually from what I've seen, GuitarTuna is the **only** app that has this kind of accuracy ) is actually very hard.

**Comment by mahdi-malv** [comment]
@ffpetrovic That's great. Thank you.
