### ISSUE TITLE
Add music notation of the note

### ISSUE THREAD

**Issue by stexniolo** [chRyNaN/Android-Guitar-Tuner#55]
Hi, i'd like to add a feature that shows an image representing the position of the recognized note.
For example, if the _C_ note is recognized, the app would have this output:
![2020-05-13 (19)](https://user-images.githubusercontent.com/53082287/81847096-68b8ff00-9553-11ea-90c7-0af94b767b3a.png)

How can i do that?

**Comment by chRyNaN** [comment]
Hi @stexniolo , this is no longer an active project but you are more than welcome to fork the project and use it yourself in accordance with the open source license.

As to your question, I'm sure you can come up with a solution to achieve this. Creating a custom Android View to draw dynamic notation will not be trivial but another option may be to use a predefined set of images. Then, when the Note is detected, match the Note name to an image resource and change the image in the ImageView beneath the Tuner View. One of the many things to consider, is that the notes detected can change rather quickly, so it might look harsh to the User if the images rapidly change. 

Good luck!
